name: dispatch

on:
 workflow_dispatch:
    inputs:
      message:
        description: '説明'
        required: true
        default: 'デフォルト値'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
     
      - name: payload sentense
        run: echo ${{ github.event.inputs.message }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
