name: dispatch

on:
 workflow_dispatch:
    inputs:
      title:
        description: 'タイトル'
        required: true
      content:
        description: '内容'
        required: true
      category:
        description: 'カテゴリ'
        required: true
        default: 'posts'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
     
      - name: payload sentense
        run: echo ${{ github.event.inputs.message }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
