# This is a basic workflow to help you get started with Actions

name: dispatch

on:
  repository_dispatch: type:[test_trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
