name: Netlify

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Checkout theme repository
        uses: actions/checkout@v2
        with:
          repository: niklasbuschmann/contrast-hugo
          path: themes/contrast-hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --gc --minify

      - name: Show Cloned Directory Tree
        run: |
          echo ${{ secrets.NETLIFY_AUTH_TOKEN }}
          echo ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './public'
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
