name: writeArticle

on:
 workflow_dispatch:
    inputs:
      title:
        description: 'タイトル'
        required: true
      category:
        description: 'カテゴリ'
        required: true
        default: 'posts'
      content:
        description: '内容'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: createArticle
        run: |
          hugo new ${{ github.event.inputs.category }}/${{ github.event.inputs.title }}.md
          ls content/${{ github.event.inputs.category }}

      - name: writeArticle
        run: echo ${{ github.event.inputs.content }} >> content/${{ github.event.inputs.category }}/${{ github.event.inputs.title }}.md

      - name: showArticle
        run: cat content/${{ github.event.inputs.category }}/${{ github.event.inputs.title }}.md
